os: linux
language: python
python:
- 3.5
- 3.6
- 3.7-dev

matrix:
  include:
  - name: Lint
    language: rust
    rust: nightly
    install:
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview
    script:
    - cargo fmt --all -- --check
    - find solutions -name '*.rs' | xargs -I {} rustfmt --check {}
    - find examples -name '*.rs' | xargs -I {} rustfmt --check {}
    - cargo clippy
    - cargo clippy -- -F clippy_pedantic -F clippy_style -F clippy_complexity -F clippy_perf -F clippy_nursery
    - cd porus_macros
    - cargo clippy
    - cargo clippy -- -F clippy_pedantic -F clippy_style -F clippy_complexity -F clippy_perf -F clippy_nursery
    - cd ..
    after_success:
    cache:
      directories:
      - $HOME/.cargo
      - $TRAVIS_BUILD_DIR/target
  - os: osx
    language: generic
    python: 3.6
    before_install:
    - curl -Lo python.pkg https://www.python.org/ftp/python/3.6.6/python-3.6.6-macosx10.6.pkg
    - sudo installer -pkg python.pkg -target /
    - /Applications/Python\ 3.6/Install\ Certificates.command
  allow_failures:
  - python: "3.7-dev"

env:
  global:
  - PATH=${PATH}:${HOME}/.cargo/bin
  matrix:
  - TRAVIS_RUST_VERSION=nightly
install:
- curl -sSf https://sh.rustup.rs/ | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rustup target add x86_64-unknown-linux-gnu; fi
- CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install cargo-update || echo "cargo-update already installed"
- CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install --git git://github.com/bhuztez/cov cargo-cov || echo "cargo-cov already installed"
- CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install-update -ag
- pip3 install -r requirements.txt
script:
- cargo test --verbose
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then find solutions -name '*.rs' | RUSTFLAGS="--cfg local -Z borrowck=mir -Z polonius" xargs -I {} python3 -mix -v generate {}.c; fi
- python3 -mix -v test
- python3 -mix -v clean
- find solutions -name '*.rs' | xargs -I {} python3 -mix -v generate {}
- find examples -name '*.rs' | xargs -I {} python3 -mix -v generate {}
- python3 -mix -v clean
- python3 -mix -v clean examples
after_success:
- cargo cov clean
- COVERAGE=1 python3 -mix -v test
- cargo cov test -v
- cargo cov report --coveralls
cache:
  pip: true
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
  - $TRAVIS_BUILD_DIR/testcases
